core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=d:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
add.interactive.usebuiltin=true
user.name=薛江涛
user.email=xjt927@126.com
credential.helper=store
http.sslverify=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/xjt927/xjt927.github.io.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.hexo.remote=origin
branch.hexo.merge=refs/heads/hexo
credential.helper=store
http.sslverify=false
